version: "3.7"
services:
  app:
    container_name: "app"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - custom
    volumes:
      - .:/app

  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: "lms_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - custom
    networks:
      - custom

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - custom

volumes:
  portainer-data:

networks:
  custom:
    driver: bridge
