# Generated by Django 5.1.4 on 2025-01-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Task',
        ),
    ]
