# Generated by Django 5.1.4 on 2025-01-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_assignment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsgroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentsgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.topic'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='StudentsGroup',
        ),
    ]
