# Generated by Django 5.1.4 on 2025-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_need_homework_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='hello'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2002-11-11'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='h', max_length=255),
        ),
    ]
